require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'app/models/marc_indexer.rb' # TODO
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'spec/support/login_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/entry_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/ability.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Naming/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/support/**/*'
    - 'spec/views/catalog/_index_links_default.html.erb_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/routing/**/*'
    - 'spec/views/**/*'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
