require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'app/models/marc_indexer.rb' # TODO
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/support/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/routing/**/*'
    - 'spec/views/**/*'

Style/Documentation:
  Enabled: false
