require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'app/models/marc_indexer.rb' # TODO
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'app/models/marc_record.rb'
    - 'lib/cicognara/catalogo_item.rb'
    - 'app/models/marc_indexer.rb'
    - 'app/controllers/versions_controller.rb'
    - 'lib/cicognara/book_indexer.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/entry_spec.rb'
    - 'spec/controllers/versions_controller_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/marc_indexer.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/marc_indexer.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/marc_indexer.rb'
    - 'app/models/marc_record.rb'
    - 'lib/cicognara/tei_indexer.rb'
    - 'app/controllers/versions_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/marc_indexer.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Naming/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/book.rb'
    - 'app/models/creator.rb'
    - 'app/models/role.rb'
    - 'app/models/subject.rb'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/version.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/support/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/routing/**/*'
    - 'spec/views/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/versions_controller_spec.rb'
    - 'spec/models/entry_spec.rb'
    - 'spec/requests/partials_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/controllers/versions_controller_spec.rb'
    - 'spec/views/versions/show.html.erb_spec.rb'

Style/Documentation:
  Enabled: false
