version: 2
jobs:
  build:
    working_directory: ~/cicognara-rails
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      SOLR_URL: "http://solr:SolrRocks@127.0.0.1:8888/solr/cicognara"
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          CICOGNARA_DB_HOST: localhost
          CICOGNARA_DB_USERNAME: cicognara
      - image: zookeeper:3.4
      - image: postgres:10.3-alpine
        environment:
          POSTGRES_USER: cicognara
          POSTGRES_DB: cicognara_test
          POSTGRES_PASSWORD: ""
      - image: solr:8.4
        command:
          - "sh"
          - "-c"
          - wget -O /tmp/security.json "https://gist.githubusercontent.com/eliotjordan/a27be341dc2e7a532bad99203e0f55b7/raw/5866efab9242f953764c1b03d17763309e22948f/security.json" && server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:2181 -cmd putfile /security.json /tmp/security.json && bin/solr -cloud -noprompt -f -p 8888 -z localhost:2181
    steps: &test_steps
      - checkout
      - run:
          name: Install node@8.17.0 (need right version for `yarn`)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v8.17.0' >> $BASH_ENV
            echo 'nvm alias default v8.17.0' >> $BASH_ENV
      - run:
          name: Check current version of node
          command: node -v
      # use bundler 2
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      # Dependencies
      # Restore the dependency cache
      - type: cache-restore
        name: Restore bundle cache
        key: cicognara-rails-{{ checksum "Gemfile.lock" }}
      - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          --jobs=4 --retry=3 '
      - run:
          name: Load config into solr
          command: |
            cd solr/config
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://solr:SolrRocks@127.0.0.1:8888/solr/admin/configs?action=UPLOAD&name=cicognara"
            curl -H 'Content-type: application/json' http://solr:SolrRocks@127.0.0.1:8888/api/collections/ -d '{create: {name: cicognara, config: cicognara, numShards: 1}}'

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: cicognara-rails-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      # project database settings
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rails db:migrate RAILS_ENV=test
      # Test
      - run: bundle exec rake rubocop
      - run: bundle exec rspec
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: tmp/capybara
      - store_artifacts:
          path: /tmp/circleci-test-results
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
