development: &default
  adapter: postgresql
  database: cicognara_development
  host: <%= ENV["CICOGNARA_DB_HOST"] %>
  username: <%= ENV["CICOGNARA_DB_USERNAME"] %>
  password: <%= ENV["CICOGNARA_DB_PASSWORD"] %>
  timeout: 5000

test:
  <<: *default
  database: cicognara_test

production: &deploy
  <<: *default
  database: <%= ENV["CICOGNARA_DB"] %>

staging:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/staging.sqlite3
